// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv cloudflare-env.d.ts`

interface CloudflareEnv {
	POD_RSS_KV: KVNamespace;
	NEXT_CACHE_WORKERS_KV: KVNamespace;
	POD_RSS_KV: string;
	NEXT_CACHE_WORKERS_KV: string;
	NEXTJS_ENV: string;
	AUDIO_SPEED: string;
	AUDIO_VOICE_ID: string;
	OPENAI_MAX_TOKENS: string;
	OPENAI_API_KEY: string;
	OPENAI_BASE_URL: string;
	OPENAI_MODEL: string;
	NEXT_STATIC_HOST: string;
	WECHAT_WEBHOOK: string;
	POD_RSS_R2: R2Bucket;
	ASSETS: Fetcher;
	POD_RSS_WORKFLOW: Workflow;
}
